### PR TITLE
Update readme with mqtt example

### PR DESCRIPTION
**Pull request by svendhoest**
Example of mqtt integration with Go-E gemini charger

### CODE REVIEW

**Comment by svendhoest** [comment]
@jonasbkarlsson can you review?

**Comment by jonasbkarlsson** [comment]
Thanks for the PR. Actually, instead of adding more examples in the readme, I'm thinking of activating the Wiki page and collect various example there instead.

**Comment by svendhoest** [comment]
I agree, it could grow to large. If you create the wiki i can maintain the Go-e part.

**Comment by jonasbkarlsson** [comment]
I have now put your contribution here [Go-e Gemini](https://github.com/jonasbkarlsson/ev_smart_charging/wiki/Go%E2%80%90E-Gemini)

**Comment by svendhoest** [comment]
Thanks Jonas.

Can you do me a favour and delete the lines with qos: "0", they are wrong...

With kind regards
Svend

**Pull request closed without merging**
