### PR TITLE
Added Dutch, Norwegian and Swedish translations.

### PR DESCRIPTION
**Pull request by jonasbkarlsson**

### CODE REVIEW

**Comment by jonasbkarlsson** [comment]
@corvy, the file name `no.json` didn't work. I changed it to `nb.json`.

**Comment by jonasbkarlsson** [comment]
@corvy, @CasparTheBridge, I have done a pre-release [v1.12.0-dev1](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.12.0-dev1). Can you check if it looks ok?

**Comment by jonasbkarlsson** [comment]
Hmm. Realized that if you `Settings->System->General->Language` set to something else than English, in order for the entity names to be translated, then also the Entity ID is being translated for newly created instances of the integration. 

Not sure that is desirable. The documentation of the integration assumed English Entity IDs, and if someone creates a new issue, it will be complicated for me to understand which entity is which...

Maybe there is a way to keep the Entity IDs in English, while the entiry name is being translated. Anyone who knows?

**Comment by corvy** [comment]
The translation works well at least. 👍 Agree that the entity names should not be translated but I guess that is not a showstopper. Have no idea how to overcome that.

**Comment by corvy** [comment]
Found a problem in my setup with this implemented. The attribute names changed, and since I have quite a few automations running that listens for changes in the attributes that becomes a problem. At least it should be mentioned as a breaking change I guess. 

Example, before this worked: 
`{{ state_attr('sensor.ev_sc_eneren_charging', 'Charging start time') != None }}`

Now this must be changed to:
`{{ state_attr('sensor.ev_sc_eneren_charging', 'charging_start_time') != None }}`

And so forth ... no big deal, but I did not notice until about a day and a half ... meanwhile my car did not charge :O

**Comment by jonasbkarlsson** [comment]
Thanks for reporting. That's not a wanted consequence. I think I can modify so that the previous attribute names will be used.

**Comment by corvy** [comment]
I am fine either way, but I think it would be good for the users to know. Of course having the untranslated strings as attributes would probably make it more consistent across installations and make it easier from a templating perspective I guess.

**Comment by corvy** [comment]
Yes, I still think its the right move. Just warn about breaking change. Its a really easy fix when you know about it.

**Comment by jonasbkarlsson** [comment]
Yes, I also think it is better to do it  right now, even though it will be an backward-incompatible change.

Also, I have now done a [v1.12.0-dev2](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.12.0-dev2) that makes sure the entity IDs always will be in English.

**Comment by corvy** [comment]
Good call. I will test.

**Comment by hmmbob** [comment]
dev2 works fine here.

**Comment by corvy** [comment]
For me also, works fine 🤙

**Pull request merged**
