### PR TITLE
Fix config entry setup warning

### LINKED ISSUE #273: Forwarding setup to config entry platforms (HA 2024.7)
HA 2024.7 will generate a new warning:
 
https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

https://github.com/jonasbkarlsson/ev_smart_charging/blob/51b426c2dcfdffc02075abe990ba01dab733f73e/custom_components/ev_smart_charging/__init__.py#L54

### PR DESCRIPTION
**Pull request by hmmbob**
Fixes #273 

Tested locally

### CODE REVIEW

**Comment by jonasbkarlsson** [comment]
@hmmbob, thanks for the PR!

**Comment by jonasbkarlsson** [comment]
Unfortunately, this caused problems with testing for HA 2024.6. So I reverted it for now, and will look at it later.

**Comment by hmmbob** [comment]
Yeah, it needs 2024.7 indeed (which is also the only version where the warning will show)

**Comment by jonasbkarlsson** [comment]
Actually, it requires 2022.8, which was the reason why I started to remove support for 2022.7 #281 (which is the oldest version currently supported by this integration). But then there were faults in the testing for 2024.6, even though it works for all other versions (from 2022.8 and up). I'm not sure if the testing problem is due to the test code or the actual code of the integration.

**Pull request merged**
